language: cpp
os: linux
compiler: gcc
sudo: required
dist: xenial

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

before_install:
    - sudo apt-add-repository --yes ppa:beineri/opt-qt-5.10.0-xenial
    - sudo apt-get -qq update

install:
    - sudo apt-get install -y qt510base qt510quickcontrols2 mesa-common-dev

before_script:
    - QTDIR="/opt/qt510"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt510/bin/qt510-env.sh

    # cmake build of the project
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/qt510/lib/cmake 

script:
    - make