language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

before_install:
    - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
    - sudo apt-get -qq update

install:
    - sudo apt-get --yes install qt55base
    - export CXX="g++-4.8"
    - export CC="gcc-4.8"

before_script:
    - QTDIR="/opt/qt55"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt55/bin/qt55-env.sh

    # cmake build of the project
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/qt55/lib/cmake 

script:
    - make