language: cpp
os: linux
compiler: 
    - gcc
    - clang
sudo: required
dist: xenial

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

before_install:
    - sudo apt-add-repository --yes ppa:beineri/opt-qt-5.10.0-xenial
    - sudo apt-get -qq update
    - pip install --user cpp-coveralls

install:
    - sudo apt-get install -y qt510base qt510quickcontrols2 mesa-common-dev

before_script:
    - QTDIR="/opt/qt510"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt510/bin/qt510-env.sh

    # cmake build of the project
    - mkdir build && cd build
    - cmake -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/opt/qt510/lib/cmake ..

script:
    - make
    - ./test/curves_test

after_success:
    - coveralls --root .. -e test -e external -E ".*gtest.*" -E ".*CMakeFiles.*" -E ".*moc.*" -E ".*qrc_qml.cpp"

